# Generated by Django 5.1.2 on 2024-11-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOutbox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=255)),
                ('event_date_time', models.DateTimeField(auto_now_add=True)),
                ('environment', models.CharField(max_length=255)),
                ('event_context', models.JSONField()),
                ('metadata_version', models.BigIntegerField()),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
