name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up environment variables
      run: echo "DJANGO_ENV_FILE=./src/core/env.ci" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build \
          --build-arg PYTHON_IMAGE_BASE=python:3.13-bullseye \
          -t myapp:latest .

    - name: Run linter
      run: |
        docker run --rm myapp:latest \
          make lint

    - name: Run tests
      run: |
        docker run --rm myapp:latest \
          make test
